Bot:
  token: MTMxMTQwMzUzNDIwOTc4MTc3MA.GwyH_P.uaD-sEToaDgUYygLo0YBs_ACdJEIdTy9Jaz_uo
  clientId: '1311403534209781770'
System:
  port: 3000
  ownerID: '392855285263499274'
  version: 1.0.0
  startTime: '2025-01-08T01:22:14.953Z'
Embed:
  embedColor: '#ff0000'
  footerText: Powered by Hex Bot
  footerIcon: https://hexmodz.com/assets/logo.png
Logs:
  enabled: true
  channelId: '1326355027765366785'
  messageDelete: true
  messageUpdate: true
  memberJoin: true
  memberLeave: true
  memberUpdate: true
  channelCreate: true
  channelDelete: true
  roleCreate: true
  roleDelete: true
  voiceStateUpdate: true
  banAdd: true
  banRemove: true
